# Generated by Django 4.2 on 2023-04-24 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pb_djworkflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_decision', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb_djworkflow.process')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
