# Generated by Django 4.2 on 2023-04-24 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('closed_at', models.DateField(null=True)),
                ('flow_class', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('init', 'Initialised'), ('running', 'Running'), ('aborted', 'Aborted'), ('failed', 'Failed'), ('done', 'Done')], default='init', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(null=True)),
                ('step', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('init', 'Initalised'), ('ready', 'Ready'), ('stall', 'Stall'), ('submitted', 'Submitted'), ('aborted', 'Aborted'), ('failed', 'Failed'), ('done', 'Done'), ('closed', 'Closed')], default='init', max_length=20)),
                ('current_job', models.CharField(blank=True, max_length=255, null=True)),
                ('log', models.TextField()),
                ('assigned_to_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_done', to=settings.AUTH_USER_MODEL)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followings', to='pb_djworkflow.task')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pb_djworkflow.process')),
                ('subprocess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supratasks', to='pb_djworkflow.process')),
            ],
        ),
    ]
